(function(){
  if(window.__v5EventRisk)return; window.__v5EventRisk=true;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function css(){if(document.getElementById('v5EventRiskCSS'))return;const s=document.createElement('style');s.id='v5EventRiskCSS';s.textContent='.v5-er{margin:12px 0;background:#fff;border:1px solid #dfe5ec;border-radius:12px;padding:14px;box-shadow:0 4px 14px #243b5310}.v5-er-head{display:flex;justify-content:space-between;align-items:center;gap:8px}.v5-er-title{font-size:17px;font-weight:900}.v5-er-level{font-size:12px;font-weight:900;border-radius:999px;padding:5px 9px}.v5-er-high{background:#fff1f0;color:#c62828}.v5-er-mid{background:#fff8e6;color:#9a6700}.v5-er-low{background:#eef8f1;color:#16834b}.v5-er-list{display:grid;gap:8px;margin-top:10px}.v5-er-item{background:#f8fafc;border-radius:9px;padding:9px 10px}.v5-er-day{font-size:11px;color:#667085;font-weight:800}.v5-er-name{font-size:14px;font-weight:900;margin-top:2px}.v5-er-note{font-size:12px;color:#475467;line-height:1.55;margin-top:3px}.v5-er-read{border-top:1px solid #e7ebf0;margin-top:10px;padding-top:9px;font-size:13px;line-height:1.65;color:#344054}@media(max-width:820px){.v5-er{padding:12px}.v5-er-note,.v5-er-read{font-size:13px}}';document.head.appendChild(s)}
  function today(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),o=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${o.year}-${o.month}-${o.day}`}
  const diff=(a,b)=>Math.round((new Date(b+'T00:00:00+08:00')-new Date(a+'T00:00:00+08:00'))/86400000);
  const label=d=>d===0?'TODAY｜今天':d===1?'D-1｜明天':d===2?'D-2｜後天':'D-3｜三日內';
  function analyze(events){const high=events.filter(e=>e.importance==='high').length,score=high*2+(events.length-high);if(score>=4)return {level:'高',cls:'v5-er-high',text:'多項重要事件集中，短線波動可能放大。建議特別觀察夜盤、隔日跳空、成交量與 P/C 是否同步異常。'};if(score>=2)return {level:'中高',cls:'v5-er-mid',text:'三日內存在重要事件，市場可能提前觀望或增加避險，留意事件公布前後量價變化。'};return {level:'一般',cls:'v5-er-low',text:'三日內暫無多項重大事件集中，主要觀察仍回到量價、籌碼與市場結構。'}}
  async function run(){css();let data;try{const r=await fetch('event-risk.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)return;data=await r.json()}catch(e){return}const d0=today(),events=(data.events||[]).map(e=>({...e,d:diff(d0,e.date)})).filter(e=>e.d>=0&&e.d<=3).sort((a,b)=>a.d-b.d),a=analyze(events);let host=document.getElementById('eventRisk72h');if(!host){const breadth=document.getElementById('breadth');if(!breadth)return;host=document.createElement('section');host.id='eventRisk72h';breadth.insertAdjacentElement('afterend',host)}host.className='v5-er';host.innerHTML=`<div class="v5-er-head"><div class="v5-er-title">未來 72 小時事件風險</div><span class="v5-er-level ${a.cls}">風險 ${a.level}</span></div><div class="v5-er-list">${events.length?events.map(e=>`<div class="v5-er-item"><div class="v5-er-day">${label(e.d)}${e.time?'｜'+esc(e.time):''}</div><div class="v5-er-name">${e.importance==='high'?'⚠️ ':'• '}${esc(e.title)}</div><div class="v5-er-note">${esc(e.note||'')}</div></div>`).join(''):'<div class="v5-er-item"><div class="v5-er-name">三日內暫無已登錄重大事件</div></div>'}</div><div class="v5-er-read"><b>事件判讀：</b>${esc(a.text)}</div>`}
  function start(){run();setInterval(run,30*60*1000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();