(function(){
 if(window.__v5EventRisk)return;window.__v5EventRisk=true;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function css(){if(document.getElementById('v5EventRiskCSS'))return;const s=document.createElement('style');s.id='v5EventRiskCSS';s.textContent=`.v5-er{margin-top:12px;border:1px solid #e4eaf1;border-radius:14px;padding:14px;background:#fff}.v5-er-head{display:flex;justify-content:space-between;gap:8px;align-items:center}.v5-er-title{font-weight:900;font-size:17px}.v5-er-level{font-weight:900;border-radius:999px;padding:5px 9px;font-size:12px}.v5-er-high{background:#fff1f0;color:#c62828}.v5-er-mid{background:#fff8e6;color:#9a6700}.v5-er-low{background:#eef8f1;color:#16834b}.v5-er-list{display:grid;gap:8px;margin-top:11px}.v5-er-item{background:#f8fafc;border-radius:10px;padding:9px 10px}.v5-er-day{font-size:11px;color:#667085;font-weight:800}.v5-er-name{font-size:14px;font-weight:900;margin-top:2px}.v5-er-note{font-size:12px;color:#475467;line-height:1.55;margin-top:3px}.v5-er-read{border-top:1px solid #e7ebf0;margin-top:10px;padding-top:9px;font-size:13px;line-height:1.65;color:#344054}@media(max-width:820px){.v5-er{padding:12px}.v5-er-title{font-size:16px}.v5-er-name{font-size:14px}.v5-er-note,.v5-er-read{font-size:13px}}`;document.head.appendChild(s)}
 function localDate(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const o=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${o.year}-${o.month}-${o.day}`}
 function daysBetween(a,b){return Math.round((new Date(b+'T00:00:00+08:00')-new Date(a+'T00:00:00+08:00'))/86400000)}
 function dayLabel(d){return d===0?'TODAY｜今天':d===1?'D-1｜明天':d===2?'D-2｜後天':`D-${d}｜三日內`}
 function analyze(events,market){let score=0;events.forEach(e=>score+=e.importance==='high'?2:1);if(events.filter(e=>e.importance==='high').length>=2)score+=2;const structure=market?.eventContext?.structure||'';const pc=Number(market?.pc?.oi);if(/量縮|盤整|分歧/.test(structure))score+=1;if(Number.isFinite(pc)&&(pc>=1.35||pc<=.75))score+=1;return score>=5?{level:'高',cls:'v5-er-high',text:'多項重要事件集中，短線波動可能放大；留意夜盤、隔日跳空與事件公布後方向反轉。'}:score>=2?{level:'中高',cls:'v5-er-mid',text:'三日內有重要事件，市場可能提前降低追價意願或增加避險；留意量能與 P/C 是否同步異常。'}:{level:'一般',cls:'v5-er-low',text:'三日內暫無多項重大事件集中，仍以量價、籌碼與市場結構為主要觀察。'}}
 async function run(){css();let data=null,market=null;try{const [a,b]=await Promise.all([fetch('event-risk.json?ts='+Date.now(),{cache:'no-store'}),fetch('market.json?ts='+Date.now(),{cache:'no-store'})]);if(a.ok)data=await a.json();if(b.ok)market=await b.json()}catch(e){}if(!data)return;const today=localDate(),events=(data.events||[]).map(e=>({...e,d:daysBetween(today,e.date)})).filter(e=>e.d>=0&&e.d<=3).sort((a,b)=>a.d-b.d);const a=analyze(events,market);let host=document.getElementById('eventRisk72h');if(!host){const breadth=document.getElementById('breadth');if(!breadth)return;host=document.createElement('div');host.id='eventRisk72h';breadth.insertAdjacentElement('afterend',host)}host.className='v5-er';host.innerHTML=`<div class="v5-er-head"><div class="v5-er-title">未來 72 小時事件風險</div><span class="v5-er-level ${a.cls}">風險 ${a.level}</span></div><div class="v5-er-list">${events.length?events.map(e=>`<div class="v5-er-item"><div class="v5-er-day">${dayLabel(e.d)}${e.time?'｜'+esc(e.time):''}</div><div class="v5-er-name">${e.importance==='high'?'⚠️ ':'• '}${esc(e.title)}</div><div class="v5-er-note">${esc(e.note||'')}</div></div>`).join(''):'<div class="v5-er-item"><div class="v5-er-name">三日內暫無已登錄重大事件</div></div>'}</div><div class="v5-er-read"><b>綜合判讀：</b>${esc(a.text)}</div>`;window.dispatchEvent(new CustomEvent('event-risk-updated',{detail:{events,analysis:a}}))}
 function start(){run();setInterval(run,30*60*1000)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();